-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Vært: 127.0.0.1:3306
-- Genereringstid: 06. 10 2022 kl. 18:56:34
-- Serverversion: 5.7.36
-- PHP-version: 7.4.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `filmoversigt`
--

-- --------------------------------------------------------

--
-- Struktur-dump for tabellen `film`
--

DROP TABLE IF EXISTS `film`;
CREATE TABLE IF NOT EXISTS `film` (
  `filmId` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `filmNavn` varchar(100) COLLATE utf8_danish_ci NOT NULL,
  `filmUdgivelsesaar` year(4) NOT NULL,
  `filmGenre` varchar(250) COLLATE utf8_danish_ci NOT NULL,
  `filmLaengde` varchar(50) COLLATE utf8_danish_ci NOT NULL,
  `filmRating` decimal(4,1) NOT NULL,
  `filmSkuespillere` varchar(250) COLLATE utf8_danish_ci NOT NULL,
  `filmInstruktoer` varchar(250) COLLATE utf8_danish_ci NOT NULL,
  `filmBeskrivelse` text COLLATE utf8_danish_ci NOT NULL,
  `filmUdkommer` datetime NOT NULL,
  `filmBillede` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`filmId`)
) ENGINE=MyISAM AUTO_INCREMENT=50 DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;

--
-- Data dump for tabellen `film`
--

INSERT INTO `film` (`filmId`, `filmNavn`, `filmUdgivelsesaar`, `filmGenre`, `filmLaengde`, `filmRating`, `filmSkuespillere`, `filmInstruktoer`, `filmBeskrivelse`, `filmUdkommer`, `filmBillede`) VALUES
(46, 'Transformers: De faldnes hævn', 2009, 'Action/Sci-fi', '150 minutter', '5.9', 'Megan Fox, Shia LaBeouf, Rachael Taylor, Mark WahlBerg', 'Michael Bay', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CDMQAA\" data-ved=\"2ahUKEwi0oaHi7cn6AhUNwAIHHRRpC8YQkCl6BAgzEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CDMQAQ\" data-ved=\"2ahUKEwi0oaHi7cn6AhUNwAIHHRRpC8YQziAoAHoECDMQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">To &aring;r efter at Sam blev involveret i kampen mellem de gode og onde k&aelig;mperobotter, de s&aring;kaldte transformers, skal han starte p&aring; college. Hans k&aelig;reste Mikaela er ikke meget for at sende Sam af sted, og Sam har da heller ikke v&aelig;ret ret l&aelig;nge p&aring; college, f&oslash;r studinen Alice begynder at l&aelig;gge an p&aring; ham.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical country of origin release date\" data-md=\"1001\" data-hveid=\"CC4QAA\" data-ved=\"2ahUKEwi0oaHi7cn6AhUNwAIHHRRpC8YQkCl6BAguEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwi0oaHi7cn6AhUNwAIHHRRpC8YQyxMoAHoECC4QAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2009-06-26 00:00:00', 't2.jpg'),
(45, 'Transformers', 2007, 'Action/Sci-fi', '144 minutter', '7.0', 'Megan Fox, Shia LaBeouf, Rachael Taylor, Mark WahlBerg', 'Michael Bay', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CDgQAA\" data-ved=\"2ahUKEwjv2avZ7cn6AhUVwAIHHfmxD8QQkCl6BAg4EAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CDgQAQ\" data-ved=\"2ahUKEwjv2avZ7cn6AhUVwAIHHfmxD8QQziAoAHoECDgQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Den kiksede Sam sparer op til at k&oslash;be en bil, s&aring; han kan imponere den l&aelig;kre Mikaela. Han ender med at k&oslash;be en robot i forkl&aelig;dning, en venligsindet Autobot, som har til opgave at beskytte Sam, da ...</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CG0QAA\" data-ved=\"2ahUKEwjv2avZ7cn6AhUVwAIHHfmxD8QQkCl6BAhtEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjv2avZ7cn6AhUVwAIHHfmxD8QQyxMoAHoECG0QAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2007-07-04 00:00:00', 't1.jpg'),
(44, 'Man of Steel', 2013, 'Action/Eventyr', '143 minutter', '7.1', 'Henry Cavill, Kevin Costner, Russell Crowe, Diane Lane', 'Zack Snyder', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CFIQAA\" data-ved=\"2ahUKEwit-p3x7Mn6AhUsNOwKHbTXCcUQkCl6BAhSEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CFIQAQ\" data-ved=\"2ahUKEwit-p3x7Mn6AhUsNOwKHbTXCcUQziAoAHoECFIQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Journalisten Clark Kent m&aring; skjule sine superkr&aelig;fter for verden, men da en ond general p&aring;t&aelig;nker at destruere Jorden, springer Manden af st&aring;l i aktion.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CEAQAA\" data-ved=\"2ahUKEwit-p3x7Mn6AhUsNOwKHbTXCcUQkCl6BAhAEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwit-p3x7Mn6AhUsNOwKHbTXCcUQyxMoAHoECEAQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2013-06-14 00:00:00', 'mos.jpg'),
(43, 'Ringenes Herre - Kongen vender tilbage', 2003, 'Fantasyfilm/Eventyr', '201 Minutter', '9.0', 'Elijah Wood, Viggo Mortensen, Cate Blanchett, Ian McKellen', 'Peter Jackson', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CDAQAA\" data-ved=\"2ahUKEwiwy6yt7Mn6AhWH6aQKHdQ8DsYQkCl6BAgwEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CDAQAQ\" data-ved=\"2ahUKEwiwy6yt7Mn6AhWH6aQKHdQ8DsYQziAoAHoECDAQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">I et fors&oslash;g p&aring; at udslette menneskeheden belejrer den onde Lord Saurons enorme styrker Minas Tirith, Gondors hovedstad.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CC4QAA\" data-ved=\"2ahUKEwiwy6yt7Mn6AhWH6aQKHdQ8DsYQkCl6BAguEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwiwy6yt7Mn6AhWH6aQKHdQ8DsYQyxMoAHoECC4QAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2003-12-17 00:00:00', 'lotr3.jpg'),
(42, 'Ringenes Herre - De to tårne', 2002, 'Fantasyfilm/Eventyr', '179 minutter', '8.8', 'Elijah Wood, Viggo Mortensen, Cate Blanchett, Ian McKellen', 'Peter Jackson', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CDAQAA\" data-ved=\"2ahUKEwjousiH7Mn6AhVTJMUKHcHeDcUQkCl6BAgwEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CDAQAQ\" data-ved=\"2ahUKEwjousiH7Mn6AhVTJMUKHcHeDcUQziAoAHoECDAQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Fra de to t&aring;rne; Orthanc i Isengard, hvor den korrupte Saruman har fremavlet en arm&eacute; p&aring; 10.000 orker og Saurons f&aelig;stning Barad-d&ucirc;r dybt inde i Mordors m&oslash;rke rige - breder sig en ond og uimodst&aring;elig magt. Den lille flok, som rejste af sted for at g&oslash;re en ende p&aring; ringen og de m&oslash;rke kr&aelig;fter, er spredt for alle vinde.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CDQQAA\" data-ved=\"2ahUKEwjousiH7Mn6AhVTJMUKHcHeDcUQkCl6BAg0EAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjousiH7Mn6AhVTJMUKHcHeDcUQyxMoAHoECDQQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2002-12-15 00:00:00', 'lotr2.jpg'),
(41, 'Ringenes herre - eventyret om ringen', 2001, 'Fantasyfilm/Eventyr', '179 minutter', '8.8', 'Elijah Wood, Viggo Mortensen, Cate Blanchett, Ian McKellen', 'Peter Jackson', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CFIQAA\" data-ved=\"2ahUKEwiDycuA7Mn6AhUbwAIHHf07AsUQkCl6BAhSEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CFIQAQ\" data-ved=\"2ahUKEwiDycuA7Mn6AhUbwAIHHf07AsUQziAoAHoECFIQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">M&oslash;rkest fyrste i Mordor - Lord Sauron - opruster. Han mangler kun &eacute;n ting for at l&aelig;gge hele Midgaard for sine f&oslash;dder og slavebinde alle dets folk - en magisk guldring med enorme kr&aelig;fter.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CF8QAA\" data-ved=\"2ahUKEwiDycuA7Mn6AhUbwAIHHf07AsUQkCl6BAhfEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwiDycuA7Mn6AhUbwAIHHf07AsUQyxMoAHoECF8QAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2001-12-19 00:00:00', 'lotr1.jpg'),
(40, 'The hunger games: Mockingjay - del 2', 2015, 'Action/Sci-fi', '137 minutter', '6.5', 'Jennifer Lawrence, Josh Hutcherson, Sam Clafin, Jena Malone', 'Francis Lawrence', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CDcQAA\" data-ved=\"2ahUKEwjJtoPE68n6AhXShqQKHeJEAsUQkCl6BAg3EAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CDcQAQ\" data-ved=\"2ahUKEwjJtoPE68n6AhXShqQKHeJEAsUQziAoAHoECDcQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Ufrivilligt holdes Katniss fanget i Distrikt 13, og eftersom Peeta er blevet hjernevasket til at udslette hende, er h&aelig;vnen p&aring; Pr&aelig;sident Snow st&oslash;rre end nogensinde. Katniss begiver sig ud p&aring; en farefuld rejse for at sl&aring; Snow ihjel.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CD0QAA\" data-ved=\"2ahUKEwjJtoPE68n6AhXShqQKHeJEAsUQkCl6BAg9EAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjJtoPE68n6AhXShqQKHeJEAsUQyxMoAHoECD0QAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2015-11-19 00:00:00', 'thg4.jpg'),
(39, 'The hunger games: Mockingjay - del 1', 2014, 'Sci-fi/action', '123 minutter', '6.6', 'Jennifer Lawrence, Josh Hutcherson, Sam Clafin, Jena Malone', 'Francis Lawrence', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CE0QAA\" data-ved=\"2ahUKEwiTs5yM68n6AhVGsaQKHSGDC8YQkCl6BAhNEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CE0QAQ\" data-ved=\"2ahUKEwiTs5yM68n6AhVGsaQKHSGDC8YQziAoAHoECE0QAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Katniss Everdeen er tilbage som frihedsk&aelig;mperen og befinder sig nu ufriviligt i det krigsh&aelig;rgede Distrikt 13. Hurtigt indser hun, at modstandsfolket har udvalgt hende som lederen i kampen for Panems overlevelse.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CFEQAA\" data-ved=\"2ahUKEwiTs5yM68n6AhVGsaQKHSGDC8YQkCl6BAhREAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwiTs5yM68n6AhVGsaQKHSGDC8YQyxMoAHoECFEQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2014-11-19 00:00:00', 'thg3.jpg'),
(38, 'The hunger games: Catching Fire', 2013, 'Action/Sci-fi', '146 minutter', '7.5', 'Jennifer Lawrence, Josh Hutcherson, Sam Clafin, Jena Malone', 'Francis Lawrence', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CDIQAA\" data-ved=\"2ahUKEwiE_O_x6sn6AhVSt6QKHQWNCc0QkCl6BAgyEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CDIQAQ\" data-ved=\"2ahUKEwiE_O_x6sn6AhVSt6QKHQWNCc0QziAoAHoECDIQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Katniss og Peeta fra Distrikt 12 er vendt hjem efter at have vundet det 74. &aring;rlige d&oslash;dsspil. Men de to vindere m&aring; hurtigt forlade deres familier for at tage p&aring; en sejrstur gennem Panem og promovere det makabre realityprogram, hvor b&oslash;rn tvinges til at k&aelig;mpe for livet.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CDoQAA\" data-ved=\"2ahUKEwiE_O_x6sn6AhVSt6QKHQWNCc0QkCl6BAg6EAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwiE_O_x6sn6AhVSt6QKHQWNCc0QyxMoAHoECDoQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2016-11-20 00:00:00', 'thg2.jfif'),
(37, 'The hunger games', 2012, 'Action/Sci-fi', '142 Minutter', '7.2', 'Wood Harrelson, Jennifer Lawrence, Lenny Kravitz, Josh Hutcherson', 'Gary Ross', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CFIQAA\" data-ved=\"2ahUKEwi9zPjS6sn6AhURKuwKHWFuBMUQkCl6BAhSEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CFIQAQ\" data-ved=\"2ahUKEwi9zPjS6sn6AhURKuwKHWFuBMUQziAoAHoECFIQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Landet Panem, er inddelt i 12 distrikter, som alle styres af det m&aelig;gtige Capitol. Hvert &aring;r skal hvert distrikt finde to repr&aelig;sentanter til at deltage i det landsd&aelig;kkende reality-show, D&oslash;dsspillet, en kunstigt skabt arena, hvor 24 deltagere tvinges til at k&aelig;mpe mod hinanden, indtil kun &eacute;n overlevende st&aring;r tilbage.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CGQQAA\" data-ved=\"2ahUKEwi9zPjS6sn6AhURKuwKHWFuBMUQkCl6BAhkEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwi9zPjS6sn6AhURKuwKHWFuBMUQyxMoAHoECGQQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2012-03-22 00:00:00', 'thg1.jpg'),
(36, 'Star Wars episode 6: Jediridderen vender tilbage', 1983, 'Sci-fi/action', '131 minutter', '8.3', 'Mark Hamill, Harrison Ford, Carrie Fisher, Peter Mayhew', 'George Lucas', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CDsQAA\" data-ved=\"2ahUKEwi4nNPH6sn6AhVN_KQKHdyvCcYQkCl6BAg7EAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CDsQAQ\" data-ved=\"2ahUKEwi4nNPH6sn6AhVN_KQKHdyvCcYQziAoAHoECDsQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Han Solo er f&aelig;ngslet af den groteske Jabba the Hutt. Luke Skywalker infiltrerer omr&aring;det og befrier heroisk sin ven. Sammen med prinsesse Leia og Lando Calrissian, leder de opr&oslash;rerne i den ultimative kamp mod Imperiet og den n&aring;desl&oslash;se Darth Vader.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CEMQAA\" data-ved=\"2ahUKEwi4nNPH6sn6AhVN_KQKHdyvCcYQkCl6BAhDEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwi4nNPH6sn6AhVN_KQKHdyvCcYQyxMoAHoECEMQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '1983-09-30 00:00:00', 'sw6.jpg'),
(34, 'Star Wars episode 4: Et nyt håb', 1977, 'Sci-fi/action', '121 minutter', '8.6', 'Mark Hamill, Harrison Ford, Carrie Fisher, Peter Mayhew', 'George Lucas', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CAoQAA\" data-ved=\"2ahUKEwjtptDV6cn6AhWCxwIHHfThDsUQkCl6BAgKEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CAoQAQ\" data-ved=\"2ahUKEwjtptDV6cn6AhWCxwIHHfThDsUQziAoAHoECAoQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">George Lucas\' klassiske rumeventyr om den smukke prinsesse Leia, den modige helt Luke Skywalker og den komiske robot R2-D2, som k&aelig;mper for at redde galaksen fra Darth Vader og m&oslash;rkets onde kr&aelig;fter.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CAwQAA\" data-ved=\"2ahUKEwjtptDV6cn6AhWCxwIHHfThDsUQkCl6BAgMEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjtptDV6cn6AhWCxwIHHfThDsUQyxMoAHoECAwQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '1977-12-26 00:00:00', 'sw4.jpg'),
(35, 'Star Wars episode 5: Imperiet slår igen', 1980, 'Action/Sci-fi', '124 minutter', '8.7', 'Mark Hamill, Harrison Ford, Carrie Fisher, Peter Mayhew', 'George Lucas', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CBAQAA\" data-ved=\"2ahUKEwjvw_b96cn6AhUrsKQKHaTOCcYQkCl6BAgQEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CBAQAQ\" data-ved=\"2ahUKEwjvw_b96cn6AhUrsKQKHaTOCcYQziAoAHoECBAQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Med nye frygtindgydende kampmaskiner lykkes det Imperiet at nedk&aelig;mpe Opr&oslash;rernes h&aelig;r. Han Solo, Prinsesse Leia og Chewbacca overlever og flygter til Cloud City. Luke ops&oslash;ger Yoda, for at forst&aelig;rke sin viden om kraften - The Force.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CBMQAA\" data-ved=\"2ahUKEwjvw_b96cn6AhUrsKQKHaTOCcYQkCl6BAgTEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjvw_b96cn6AhUrsKQKHaTOCcYQyxMoAHoECBMQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '1980-08-15 00:00:00', 'sw5.jpg'),
(32, 'Star Wars episode 2: Klonernes angreb', 2002, 'Action/Sci-fi', '142 Minutter', '6.6', 'Ewan  McGregor, Lian Nesson, Natalie Portman, IanMcDiarmid, Hayden Christensen', 'George Lucas', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CEAQAA\" data-ved=\"2ahUKEwiGzueg6cn6AhWNjKQKHW-NB8UQkCl6BAhAEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CEAQAQ\" data-ved=\"2ahUKEwiGzueg6cn6AhWNjKQKHW-NB8UQziAoAHoECEAQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Galaksen har gennemg&aring;et store forandringer de sidste 10 &aring;r, og en separatistbev&aelig;gelse som omfatter hundredevis af planeter truer med at &oslash;del&aelig;gge den.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CEoQAA\" data-ved=\"2ahUKEwiGzueg6cn6AhWNjKQKHW-NB8UQkCl6BAhKEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwiGzueg6cn6AhWNjKQKHW-NB8UQyxMoAHoECEoQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2002-05-16 00:00:00', 'sw2.jpg'),
(33, 'Star Wars episode 3: Sith-fyrsternes hævn', 2005, 'Action/Sci-fi', '140 minutter', '7.6', 'Ewan  McGregor, Lian Nesson, Natalie Portman, IanMcDiarmid, Hayden Christensen', 'George Lucas', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CA8QAA\" data-ved=\"2ahUKEwjD-f-o6cn6AhVmMOwKHdSaDMUQkCl6BAgPEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CA8QAQ\" data-ved=\"2ahUKEwjD-f-o6cn6AhVmMOwKHdSaDMUQziAoAHoECA8QAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Anakin begynder at f&aring; mareridt igen, og det g&aring;r op for ham, at som han foruds&aring; hans mors d&oslash;d, har han nu forudset gravide Padm&eacute; Amidalas d&oslash;d, og Palpatine fors&oslash;ger at lokke Anakin til den m&oslash;rke side af Kraften, ved at omtale en kraft der er s&aring; m&aelig;gtig at den kan forhindre folk fra den visse d&oslash;d.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical country of origin release date\" data-md=\"1001\" data-hveid=\"CA4QAA\" data-ved=\"2ahUKEwjD-f-o6cn6AhVmMOwKHdSaDMUQkCl6BAgOEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjD-f-o6cn6AhVmMOwKHdSaDMUQyxMoAHoECA4QAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2005-05-19 00:00:00', 'sw3.jpg'),
(31, 'Star Wars Episode 1: Den usynlige fjende', 1999, 'Action/Sci-fi', '136 minutter', '6.5', 'Ewan  McGregor, Lian Nesson, Natalie Portman, IanMcDiarmid', 'George Lucas', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CFoQAA\" data-ved=\"2ahUKEwi68LL46Mn6AhUSjaQKHUi8CMYQkCl6BAhaEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CFoQAQ\" data-ved=\"2ahUKEwi68LL46Mn6AhUSjaQKHUi8CMYQziAoAHoECFoQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Anakin Skywalker, en ung mand med overnaturlige kr&aelig;fter, bliver tr&aelig;net og vejledt af den gamle og vise Jedi-ridder, Obi-Wan Kenobi. Hvad ingen ved er, at Anakin en dag vil forvandles til den onde og m&aelig;gtige Darth Vader.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CGkQAA\" data-ved=\"2ahUKEwi68LL46Mn6AhUSjaQKHUi8CMYQkCl6BAhpEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwi68LL46Mn6AhUSjaQKHUi8CMYQyxMoAHoECGkQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '1999-07-19 00:00:00', 'sw1.jpg'),
(30, 'Allegiant', 2016, 'Action/Sci-fi', '120 minutter', '5.6', 'Shailene Woodly, Theo James, Miles Teller, Kate Winslet', 'Robert Schwentke', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CDcQAA\" data-ved=\"2ahUKEwjvvZOT6Mn6AhWGLewKHdNKAsYQkCl6BAg3EAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CDcQAQ\" data-ved=\"2ahUKEwjvvZOT6Mn6AhWGLewKHdNKAsYQziAoAHoECDcQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Tris og Four bev&aelig;ger sig udenfor den mur, der omslutter Chicago. Nu m&aring; de for f&oslash;rste gang forlade den eneste by, de nogensinde har kendt - og dermed ogs&aring; deres familie. P&aring; den anden side af muren bliver alt vendt p&aring; hovedet, og den sandhed de troede, de havde opdaget, ser pludselig chokerende anderledes ud.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CD0QAA\" data-ved=\"2ahUKEwjvvZOT6Mn6AhWGLewKHdNKAsYQkCl6BAg9EAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjvvZOT6Mn6AhWGLewKHdNKAsYQyxMoAHoECD0QAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2016-03-16 00:00:00', NULL),
(29, 'Insurgent', 2015, 'Action/Sci-fi', '119 minutter', '6.2', 'Shailene Woodly, Theo James, Miles Teller, Kate Winslet', 'Robert Schwentke', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CAYQAA\" data-ved=\"2ahUKEwjc84DP58n6AhUixQIHHXb8BMUQkCl6BAgGEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CAYQAQ\" data-ved=\"2ahUKEwjc84DP58n6AhUixQIHHXb8BMUQziAoAHoECAYQAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Chicago er blevet delvist udslettet. Den overlevende befolkning har delt sig i fem fraktioner alt efter individuelle livsholdninger og ideologier. Tris har fundet ud af, at hun er Divergent. En unik og eftertragtet evne, der medf&oslash;rer, at hun kan bev&aelig;ge sig p&aring; tv&aelig;rs af fraktioner.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical country of origin release date\" data-md=\"1001\" data-hveid=\"CAwQAA\" data-ved=\"2ahUKEwjc84DP58n6AhUixQIHHXb8BMUQkCl6BAgMEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjc84DP58n6AhUixQIHHXb8BMUQyxMoAHoECAwQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2015-03-16 00:00:00', 'Insurgent.jpg'),
(28, 'Divergent', 2014, 'Sci-fi/action', '139 minutter', '6.6', 'Shailene Woodley, Theo james, Miles Teller, Kate Winslet', 'Neil Burger', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CC0QAA\" data-ved=\"2ahUKEwianuWp58n6AhWJsaQKHasxC8YQkCl6BAgtEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CC0QAQ\" data-ved=\"2ahUKEwianuWp58n6AhWJsaQKHasxC8YQziAoAHoECC0QAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">I et fremtidigt samfundet, som er delt ind i fem fraktioner, der hver repr&aelig;senterer forskellige dyder, skal teenagers v&aelig;lge, om de vil blive i deres nuv&aelig;rende fraktion, eller om de vil skifte for resten af deres liv. Tris Prior tager et valg, der overrasker alle.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CCsQAA\" data-ved=\"2ahUKEwianuWp58n6AhWJsaQKHasxC8YQkCl6BAgrEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwianuWp58n6AhWJsaQKHasxC8YQyxMoAHoECCsQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2014-04-10 00:00:00', 'Divergent.jpg'),
(47, 'Transformers: Dark for the moon', 2011, 'Action/Sci-fi', '154 minutter', '6.2', 'Megan Fox, Shia LaBeouf, Rachael Taylor, Mark WahlBerg', 'Michael Bay', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CD0QAA\" data-ved=\"2ahUKEwjd6LWA7sn6AhVTxgIHHbdnCcYQkCl6BAg9EAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CD0QAQ\" data-ved=\"2ahUKEwjd6LWA7sn6AhVTxgIHHbdnCcYQziAoAHoECD0QAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Autobotterne Bumblebee, Ratchet, Ironhide, Mirage, Wheeljack og Sideswipe er tilbage anf&oslash;rt af Optimus Prime. Det er tid til det endelige opg&oslash;r med de onde deceptikoner, som er ude efter h&aelig;vn.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CEoQAA\" data-ved=\"2ahUKEwjd6LWA7sn6AhVTxgIHHbdnCcYQkCl6BAhKEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwjd6LWA7sn6AhVTxgIHHbdnCcYQyxMoAHoECEoQAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2011-06-29 00:00:00', 't3.jpg'),
(48, 'Transformers: Age of Extinction', 2014, 'Action/Sci-fi', '165 minutter', '5.6', 'Megan Fox, Shia LaBeouf, Rachael Taylor, Mark WahlBerg', 'Michael Bay', '<div class=\"wDYxhc\" data-md=\"50\" data-hveid=\"CC8QAA\" data-ved=\"2ahUKEwiKlZOs7sn6AhWNraQKHbj6DcYQkCl6BAgvEAA\">\r\n<div class=\"PZPZlf hb8SAc\" data-attrid=\"description\" data-hveid=\"CC8QAQ\" data-ved=\"2ahUKEwiKlZOs7sn6AhWNraQKHbj6DcYQziAoAHoECC8QAQ\">\r\n<div>\r\n<div>\r\n<div class=\"kno-rdesc\">Fire &aring;r efter den &oslash;del&aelig;ggende kamp mellem Autobots og Decepticons, der n&aelig;rmest j&aelig;vnede Chicago med jorden, har regeringen mistet sin tiltro til de m&aelig;gtige Transformers. Som resultat s&aelig;ttes den paranoide regeringsrepr&aelig;sentant, Harold Attinger, til at jage k&aelig;mperobotterne, s&aring; USA igen kan blive et trygt sted at leve.</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"wDYxhc\" data-attrid=\"kc:/film/film:theatrical region aware release date\" data-md=\"1001\" data-hveid=\"CE4QAA\" data-ved=\"2ahUKEwiKlZOs7sn6AhWNraQKHbj6DcYQkCl6BAhOEAA\">\r\n<div class=\"Z1hOCe\">\r\n<div class=\"zloOqf PZPZlf\" data-ved=\"2ahUKEwiKlZOs7sn6AhWNraQKHbj6DcYQyxMoAHoECE4QAQ\">&nbsp;</div>\r\n</div>\r\n</div>', '2014-06-26 00:00:00', 't4.jpg');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
